package com.microsoft.campaign.mobileuetsdk.conf;

/**
 * Created by yaqi@microsoft.com
 * Description: define parameters variable
 */
public final class ParameterConf {
    // required caller input param
    public static final String TAG_ID = "ti";
    public static final String EVENT_ACTION = "ea";   //Event action (custom value passed by advertiser)
    public static final String APP_ID = "Appid"; // It is generated by account manager, or generate directly on Campaign Platform

    // required background param

    public static final String MOBILE_USER_ID = "MUserid"; //IDFA in iOS or Android AdID
    public static final String UET_VERSION = "Ver";
    public static final String SESSION_ID = "sid"; //one runtime one session
    public static final String EVENT_TYPE = "evt"; //Event type (page load or custom)
    public static final String RANDOM_NUMBER = "rn";//It will be changed when app is reinstalled, encrypted by md5

    // optional caller input param
    public static final String WEB_MUID = "WebMUID"; //MUID from web cookie ID
    public static final String WEB_ANID = "WebANID"; //ANID from web cookie ID
    public static final String CUSTOMER_USER_ID = "CUserid"; //from customer’s system that uniquely identifies the user
    public static final String MID = "mid"; //Used to relate page load and any custom events passed with each other.
    public static final String EVENT_CATEGORY = "ec"; //Event category (custom value passed by advertiser)
    public static final String EVENT_LABEL = "el";
    public static final String EVENT_VALUE = "ev";
    public static final String VARIABLE_REVENUE = "gv";          // Variable revenue (custom value passed by advertiser)
    public static final String VARIABLE_REVENUE_CURRENCY = "gc"; //Variable revenue currency (custom value passed by advertiser)
    public static final String KEYWORD = "kw";
    public static final String ITEMS = "items";//It will be changed when app is reinstalled, encrypted by md5

    // optional background param
    public static final String DEVICE_UUID = "UUID"; //from customer’s system that uniquely identifies the user
    public static final String SCREEN_HEIGHT = "sh";
    public static final String SCREEN_WIDTH = "sw";
    public static final String DEVICE_OS_VERSION = "osv"; //Device OS version
    public static final String DEVICE_TYPE = "dt"; //Device type
    public static final String DEVICE_MODEL = "dm"; //Device model

    public static final String BRAND = "mbd";
    public static final String CPU_ABI = "mca";
    public static final String HOST = "mh";
    public static final String HARDWARE = "mhw";
    public static final String DISPLAY = "mdp";
    public static final String OS_TIME = "most";
    public static final String TIME_ZONE = "mtz";
    public static final String LANGUAGE = "mlg";
    public static final String DEVICE = "mdc";
    public static final String COUNTRY = "mct";
    public static final String VERSION_SDK = "msdk";
    public static final String MOBILE_UET_SDK_VERSION = "musv";
    public static final String LONGITUDE = "mlo";
    public static final String LATITUDE = "mla";
    public static final String EVENT = "event";
    public static final String PRE_EVENT_RANDOM_ID = "perandomid";          // previous event id
    public static final String EVENT_RANDOM_ID = "erandomid"; // Generated by a random string
    public static final String NETWORK_OPERATOR_NAME = "non";//CMCC

    //public usage param
    public static final String LOG_TIME = "logtime";
    public static final String PARAMS = "params";
    public static final String DEFAULT = "";
    public static final String FORMAT = "format";
    public static final String EXTRAINFO = "extrainfo";
    public static final String PACKAGE_NAME = "packagename";
    public static final String EVENTS_INFO = "eventsinfo";
    public static final String APP_NAME = "appname";
    public static final String APP_VERSION = "appversion";
    public static final String DEVICE_OS = "deviceos"; //Android IOS
    public static final String SEND_TIME = "sendtime"; //record this request's time
    public static final String WEB_USER_ID = "wuid"; //This id is passed when the app is woken up.
    public static final String ANDROID_ID = "aid";//It will be changed when app is reinstalled, encrypted by md5


    /*Ad click information, generated at ad click time and appended to the landing page URL when auto-tagging of Microsoft Click ID is enabled.
    Format: GUID followed by extra byte indicating whether the current value is a new one (unique to that session), as in "cdd4afcccb1c9a4cad9544dd7e5006d5-1". Note:
    This value will be "N" if cookies are blocked by the browser or no ad click information exists in cookie, and the msclkid parameter isn't in the landing page URL.
    The Microsoft Click ID will have "1N" added to the end if cookies are blocked by the browser and the msclkid parameter is in the landing page URL.
    Cookie name: _uetmsclkid
    Cookie expiration date: 90 days*/
    public static final String MS_CLICK_ID = "msclkid";


    public static final String PARAM_VALID = "The parameter is valid.";
    public static final String PARAM_INVALID = "The parameter is invalid.";
    public static final String PARAM_NULL = "The parameter is null.";
    public static final String UET_VERSION_VALUE = "2";
    public static final String EVENT_TYPE_CUSTOM = "custom";
    public static final String PAGE_TYPE_HOME = "home";
    public static final String PAGE_TYPE_SEARCHRESULTS = "searchresults";
    public static final String PAGE_TYPE_CATEGORY = "category";
    public static final String PAGE_TYPE_PRODUCT = "product";
    public static final String PAGE_TYPE_CART = "cart";
    public static final String PAGE_TYPE_PURCHASE = "purchase";
    public static final String PAGE_TYPE_OTHER = "other";
}
