# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage:  windows-latest 

steps:
- task: CredScan@3
  inputs:
    verboseOutput: true

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High' 
- task: Semmle@1
  env:
    
  inputs:
    sourceCodeDirectory: '$(Build.SourcesDirectory)'
    language: 'java'
    querySuite: 'Recommended'
    timeout: '1800'
    ram: '16384'
    addProjectDirToScanningExclusionList: false
    disallowBuildIfAntivirusScanningEnabled: false